language: php

php:
  - 5.4

env:
  global:
    - PNAME='demo-ci'
    - PSITE='demo-ci'
    - PUUID='445bb8f4-2088-4b79-9f2a-f436a18e683c'
    - PSOURCE='dev'
    - secure: "RyO2KV7404nXZCoEPgld9Mr1TBLPOBC0itjyqrF0EcoU1hC8641A0s/OU+emVGvBskdA+b5HZUprF561C060AgOVftiYxzMYTOTT/YDbdTCuIpRKx3arKMRUc9T+1NKEvMFAyAx56l7jX5bobFp3W1KMHhLny/8UJ+osJ5CBRoy0DTYSS85whBMhJb0AHIXTf2umVbpZ8qxn4CfALxV6eohGKilGc19JDVqdvP6qFHsHErNYeRnE2Jp8Oo/viVUWWxePMRf/n/RlyUjwr7Od17dSwDI7cAValRAQ43zFYPsFiNMUBlWKubKqM9laG6n2vZ1ZhmRb4DV8iRXfinzpQRDsDJ7sRGiZ4jnRNBVTpdpGfVPGX23M7b1hR/c67R3oLr+CFsJmMnR3rOWK4a/tb7dcTMzE++f8Myf0SyZrhlddHTjqQKqNLZa5jVQsO+j6dWRWtmpDgXX1/85ScwiETf6/iyaoYB61ghGm7I7uloxC8JBE2GtUN/QxUzY4uaBd1xRRocGty/m6VE98FqW0QrWBgBdj2kuaV/uyzV37UxdaIJj5sG1vMCHpt+iGSdRQGSjetkkgr8jeS8xvV+dyqqlHmbxikFTJVIdBugErj39WqZLhkwUIp48xwABz2QHO5HmJ1TMmc5bQFSt9Uxj/GN4iG5CtYBKWztGRZdi5ZLQ="
    - secure: "nphbuP7Cjz3VIdtNwAoeasy4Aw5pGyXYPt0dnXigjFYTeub9a8Ok7cA+uFmN/Ep1yibefvJ48uTXyf84WzSl11gGlGHho4R1QV1zYqu6vpoRsMu67VhALBe03DWdBWDKC+2thSdYXcVH4YqmMAqchOHCCvBtssXzUecTm4ghdjPezbg2sXaTyxSZduT5bGkq70e75mmVVF50UUsrZj5LboXCOTkDaxyVVTycJnMFbCJNBmIzmnLR1lti+C7eGbaxPsZhAYgLGWHeyT9UGs3AhLTu1QiYV6hevHx5/m0pIrZEuJPXClW9EHpGI7aaoVdExyD6Qv0pLqATCbV+BIF7PlycEt3CuecnnCCkwE6IRtFGBeIPdxa/o4QRWiPVsQ9cRPSXW8McBbVCBtcIWtMeJyjprRJWaxokYEyzO5/LqB2pINyWX42SWoHPOa2dEWy2iNImaMmOu8u1/aX6u254Z3p0OycsPWMEGuiZruqAzsBTGXlP/JnanNZwOMZ4iJp6lHdv7q6fzfdgIvkq/NvmYn/ETI37zUhm/a6kiM/Pmo5sIjc5CFFHZIwjXl5K4Zbl3hua5DgKpYuryUcsHMrBvouAl31CHgWozfOuFlrcRQBYQ2A+JvhChLck7qDWLCU9k0IfjDU/CW2Y71FeZXrCbFekYf+C1ijp8gnJ5g0uG2g="
    - PHOST='https://$TRAVIS_BRANCH-$PNAME.pantheon.io'

before_install:
  - sudo apt-get update > /dev/null

  - composer self-update
install:
  - echo "StrictHostKeyChecking no" > ~/.ssh/config
    # install php packages required for running a web server from drush on php 5.3
  - sudo apt-get install -y --force-yes php5-cgi php5-mysql

  # install drush globally
  - composer global require drush/drush:7.*

  # add composer's global bin directory to the path
  # see: https://github.com/drush-ops/drush#install---composer
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  # Install terminus.
  - git clone https://github.com/pantheon-systems/terminus.git $HOME/.drush/terminus
  - cd $HOME/.drush/terminus
  - composer update --no-dev
  - drush cc drush
  - echo "sendmail_path='true'" >> `php --ini | grep "Loaded Configuration" | awk '{print $4}'`

script:
  # stand up drupal
  - cd $TRAVIS_BUILD_DIR
  - composer install
  - npm install && npm update
  - cd sites/all/themes/manati
  - npm install && npm update
  - drush site-install manati -y --db-url=mysql://root@localhost/cidemo --db-su='root' --db-su-pw='' --site-name='CI-Demo'
  - drush updb -y && drush fra -y
  - drush cc all
  # Run behat tests
  - cd $TRAVIS_BUILD_DIR
  - drush runserver --server=builtin 8082 --strict=0 &
  - sleep 10
  - grunt
after_script:
  - drush status

after_success:
  - echo $TRAVIS_BRANCH
  - echo $TRAVIS_PULL_REQUEST
  - if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST != 'false' ] ; then git remote add pantheon ssh://codeserver.dev.$PUUID@codeserver.dev.$PUUID.drush.in:2222/~/repository.git && git push pantheon $TRAVIS_BRANCH && drush psite-ecreate $PUUID $TRAVIS_BRANCH --source=$PSOURCE || true && drush paliases && drush cc drush && cd $HOME && drush @pantheon.$PNAME.$TRAVIS_BRANCH updb -y --strict=0 && drush @pantheon.$PNAME.$TRAVIS_BRANCH fra -y --strict=0 ; fi
  - if [ $TRAVIS_BRANCH = 'master' ] && [ $TRAVIS_PULL_REQUEST = 'false' ] ; then git remote add pantheon ssh://codeserver.dev.$PUUID@codeserver.dev.$PUUID.drush.in:2222/~/repository.git && git push pantheon $TRAVIS_BRANCH && drush paliases && drush cc drush && cd $HOME && drush @pantheon.$PNAME.$TRAVIS_BRANCH updb -y --strict=0 && drush @pantheon.$PNAME.$TRAVIS_BRANCH fra -y --strict=0 ; fi
notifications:
#  irc: irc.freenode.org#elmsln

#  email: false
  slack:
    rooms:
      - secure: "krMbpPDhjEkP7G8VPb2CHuxpDbu3gnP8GjJpZl6FWz74vAi1M+oZ3RNKVUANQ/9A/pX1BmnhcKnCPBOzrBuDdPO8xDuVQ9rTmSYu8ZYXDy2UHHD/r0awaORc8TyZ3JeSFmGYCKTZBbTOl2sijuVQe3s1MO+XvPKJHZE40KHEEK1ytjJ8b5bWXlvzGYhsuqW6nRKir/19lyb5yEPnWMaEAxwjacLyeZn2LxNUFYdzcAMJuVoiU/9zNUuHLrBk2P/+/cXNH3yhR6VESB2deSF3k/mlPN4rlMK/IMazx+XF13SB0qsx/30CMlcZSsVk1n2myxisCWsV0ITBjiWQDJcPsgdR0EgFhkXsBKWXuHO8dhRoT1UsmHVXLrL9D0ite3PF50fCOtDVYiHMuWm9tFGKo2xzKqcuhcHjkCY68Co9fmTP4uEgMIf2uGrmJhVWrsmcDCVwWtMbwLu5n5TcX2U1a4rhYUnAvmAwiHoX+pmb00b3XbaM6Kl45/Uz40PhZRZ19+MhvGkx4FdMcR33h+TcaqnXY6YYuPSHAn4Cx9c72xn5rTsJ1EWWcKJBtv2kIxTfss0k7tB+UQHXvSJyQfmIyWrTsZ10PG97td2p1+IS1VzZmeIbqyCqDiUjBLSXmILE4ps9WNmCMXv/UWCGBFG+5oZTedIOh/AmEybA041l1AY="
#      - elmsln:WmKTRMe7k3IjprunaAVV3Jjg#code

