<?php

/**
 * @file
 * Contains install, update and some related hooks for manati deployment module.
 */

/**
 * Implements hook_install().
 */
function manati_deploy_install() {
  // Do your custom stuff here.
  variable_set('theme_default', 'manati');
}

/**
 * Explain what is this hook about.
 */
function manati_deploy_update_7000() {
  // Do your custom stuff here.
  // Remember to update number in function name.
}
